### ISSUE TITLE
Latest / version-specific Substrait support

### ISSUE THREAD

**Issue by Advitya17** [substrait-io/substrait-validator#19]
We've been looking to use the Substrait validator to generate Substrait plans from proto bytes representing different query plans (from DuckDB, as one example). I was told the current PYPI release is based on Substrait 0.3.0, and were wondering if the substrait support may be upgraded for the validator? 

Alternatively, it looks like several tools seeking to convert different query plans to substrait may have their implementations working for specific versions of substrait (eg - as of writing this, [DuckDB API](https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/tests/extensions/substrait/test_substrait.py) supports Substrait 0.12). Hence I'm also curious if there may be different PYPI versions of the substrait validator, which can be utilized to check plan validity / generate substrait plans from the binary data representing the corresponding substrait versions?

Thank you very much!

**Comment by jvanstraten** [comment]
Thank you for your interest!

My original idea was for the validator to be made part of the main Substrait repository and be upgraded along with Substrait itself, but for various reasons (the complexity of the validator being a big one) it didn't end up happening this way. Therefore, best case scenario it would lag behind by a week or two, but my intention was indeed for there to be a release parallel to every Substrait release (from some point onward), though the version numbers are unlikely to match (I'll put up a matrix somewhere once this becomes more relevant). Even better would be to support multiple versions at once, but Substrait is still a bit too unstable for that.

Unfortunately however, the current state is that there is not a lot of activity in this project aside from me; @cpcloud is already juggling some twenty-ish projects at once and @mbrobbel just went on parental leave. In fact, the PR for 0.3.0 support is still open without reviews (#14); the only reason that the version on PyPI has those changes in it already is because I made test releases based on my own bleeding edge version that includes all open pull requests. If by any chance you'd be interested in helping out for the foreseeable future or know someone who might be, I'd also be happy to hop into a call at some point to help get you/them started sometime, though I'm afraid I'll be AFK for the majority of this and next week.

If not, I personally wouldn't mind maintaining it on my own until someone else steps up, but after merging 3 months and ~35k line's worth of "initial commits" through, the rest of the Substrait community rightfully told me to take it down a couple notches :) Worst case scenario I'll end up forking it and maintaining it at my own discretion as `substrait-validator-unofficial` for the time being.

**Comment by jvanstraten** [comment]
Update: after some internal deliberation we've decided that I'll just maintain the validator on my own for the time being. I'll get to work upgrading the validator to the latest version tomorrow.

**Comment by jvanstraten** [comment]
The latest version of the validator is now back in sync with Substrait! I also intend to do at least one release before each breaking change in Substrait, so you should be able to swap out validator versions for different levels of Substrait support. Until I find a better place for it, the version correspondence matrix is in the main README.md file. I don't intend to backport new validation features to older Substrait versions for the time being, though; Substrait still changes too much for that the be worthwhile IMO.
